#声明storageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: course-nfs-storage
provisioner: fuseim.pri/ifs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sc-demo
spec:
  replicas: 1
  serviceName: "nginx"
  selector:
    matchLabels:
      app: sc-web
  template:
    metadata:
      labels:
        app: sc-web
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        #PVC的名称
        name: www
        #给PVC指定storage-class，让storage-class动态的创建PV
        annotations:
          volume.beta.kubernetes.io/storage-class: "course-nfs-storage"
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Mi