apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
      labels:
        name: mysql-pod
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          #Always 总是拉取镜像
          #IfNotPresent 本地有则使用本地镜像,不拉取
          #Never 只使用本地镜像，从不拉取，即使本地没有
          #如果省略imagePullPolicy  策略为always
          imagePullPolicy: IfNotPresent
          # 新版本镜像有更新，需要使用下面的认证插件环境变量配置才会生效
          args:
            - --default_authentication_plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mydata
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 3306
  selector:
    name: mysql-pod

#授权root用户远程连接。进入容器中执行命令：
# grant all privileges on *.* to 'root'@'%' identified by 'root' with grant option;
# flush privileges;

