server:
  port: 8017

spring:
  # 一个实体类对应两张表，覆盖
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
      datasource:
        # 数据源 db0,db1
        names: db0,db1
        # 第一个数据库
        db0:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://127.0.0.1:3306/testdatasource1?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
          username: root
          password:
        # 第二个数据库
        db1:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://127.0.0.1:3306/testdatasource2?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
          username: root
          password:
      # 打印执行的数据库以及语句
      props:
        sql:
          show: true
        # 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
        # 分库策略
      sharding:
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: db$->{id % 2}
        # 分表策略 其中user为逻辑表 分表主要取决于age行
        tables:
          user:
            actual-data-nodes: db$->{0..1}.user_$->{0..1}
            table-strategy:
              inline:
                sharding-column: age
                algorithm-expression: user_$->{age % 2}


