hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
    threadpool:
        default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
logging:
    config: classpath:logback.xml
management:
    endpoint:
        health:
            show-details: ALWAYS
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    boot:
        admin:
            client:
                url: http://114.67.102.137:8001
    sleuth:
        enabled: true
        http:
            legacy:
                enabled: true
xxl:
    job:
        accessToken: ''
        admin:
            addresses: http://114.67.102.137:8088/xxl-job-admin
        executor:
            appname: myJob
            ip: ''
            logpath: /data/applogs/xxl-job/jobhandler
            logretentiondays: -1
            port: 9999
