
spring:
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  boot:
    admin:
      client:
        url: http://114.67.102.163:8001   #admin客户端地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback.xml

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://114.67.102.117:8088/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9999

feign.sentinel.enabled: true