
business:
  thread-pool-executor:
    threadPools:
      hanyi:
        corePoolSize: 10
        maxPoolSize: 10
        threadNamePrefix: keji
      keji:
        corePoolSize: 10
        maxPoolSize: 10
        threadNamePrefix: hashiqi


