server:
    port: 8004
    servlet:
        context-path: /hanyi-daily

#日志級別
logging:
    level:
        root: info

spring:
    datasource:
        primary:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/testdatasource1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
            username: root
            password:
        secondary:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/testdatasource2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
            username: root
            password:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

keji.id: 1
keji.name: 韩毅
keji.age: 20

person:
    name: 柯基
    age: 21
    stringList:
        - 柴犬
        - 哈士奇
        - 小短腿
    bookList:
        - bookName: 销毁
          count: 20
        - bookName: 创建
          count: 22
