
business:
  thread-pool-executor:
    threadPools:
      hanyi:
        corePoolSize: 5
        maxPoolSize: 5
        threadNamePrefix: keji
      keji:
        corePoolSize: 5
        maxPoolSize: 5
        threadNamePrefix: hashiqi


