server:
  port: 8019

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://192.168.243.128:8123/default
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000


#mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hanyi.clickhouse.pojo
  configuration:
    # 关闭驼峰自动转换
    map-underscore-to-camel-case: false
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT

