server:
  port: 8006
  servlet:
    context-path: /hanyi-cache

spring:
  #redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 1 #指定库名
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        maxActive: 10
        maxIdle: 10
        minIdle: 1
        maxWait: 10000 #连接池最大等行时间 -1没有限制

