apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    name: mongodb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-pod
  template:
    metadata:
      labels:
        name: mongodb-pod
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2.1
          command:
            - sh
            - -c
            - "exec mongod -f /data/mongodb/conf/mongodb.conf"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: mongodb-config
              mountPath: /data/mongodb/conf/
            - name: data
              mountPath: /data/mongodb/
      volumes:
        - name: mongodb-config
          configMap:
            name: mongodb-conf
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc

---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: mongodb
  name: mongodb-service
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      nodePort: 27017
  selector:
    name: mongodb-pod

