
hystrix:
  threadpool:
    default:
      coreSize: 1000  #并发执行的最大线程数，默认10
      maxQueueSize: 1000  #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500  #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

