apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: nginx-demo
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: nginx-demo-http
      nodePort: 30001
